#:schema node_modules/wrangler/config-schema.json
name = "devbox-1983"
main = "src/index.js"
compatibility_date = "2025-08-13"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "db0eb2636a11d55bc0c0165cffae975a" }
]
